# Generated by Django 5.1.3 on 2025-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Two wheeler', 'Two wheeler'), ('Three wheeler', 'Three wheeler'), ('Four wheeler', 'Four wheeler'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='working_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='working_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
