# Generated by Django 5.1.3 on 2025-01-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_mechanicprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='verification_document',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='working_time_from',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='working_time_to',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='vehicle_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('three_wheeler', 'Three Wheeler'), ('four_wheeler', 'Four Wheeler'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='working_time_from',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='working_time_to',
            field=models.TimeField(default='18:00'),
        ),
    ]
