# Generated by Django 5.1.3 on 2025-01-15 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0003_remove_mechanicprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanic.mechanic'),
        ),
    ]
