# Generated by Django 5.1.3 on 2025-01-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0005_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='created_at',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='request',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='contact_number',
            field=models.CharField(default='tyrjjr', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='issue',
            field=models.CharField(default='yrty', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='place',
            field=models.CharField(default='jhgjg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_type',
            field=models.CharField(default='jkjh', max_length=50),
            preserve_default=False,
        ),
    ]
