# Generated by Django 5.1.3 on 2025-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0006_rename_created_at_request_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='working_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='working_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
