# Generated by Django 5.1.3 on 2025-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0007_mechanicprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('two wheeler', 'Two wheeler'), ('three wheeler', 'Three wheeler'), ('four wheeler', 'Four wheeler'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
