# Generated by Django 5.1.3 on 2025-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0008_alter_mechanicprofile_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='vehicle_type',
            field=models.CharField(choices=[('two wheeler', 'Two Wheeler'), ('three wheeler', 'Three Wheeler'), ('four wheeler', 'Four Wheeler'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
